CREATE TABLE "event_types" (
  "name" varchar PRIMARY KEY,
  "description" varchar
);

CREATE TABLE "player_roles" (
  "name" varchar PRIMARY KEY,
  "description" varchar,
  "is_staff" boolean NOT NULL
);

CREATE TABLE "server_types" (
  "name" varchar PRIMARY KEY,
  "description" varchar
);

CREATE TABLE "player_sessions" (
  "session_id" varchar(36) PRIMARY KEY,
  "visit_id" varchar NOT NULL,
  "player" varchar NOT NULL,
  "server" varchar NOT NULL,
  "started_at" timestamptz NOT NULL,
  "ended_at" timestamptz NOT NULL
);

CREATE TABLE "player" (
  "uuid" varchar(36) PRIMARY KEY,
  "username" varchar(16) NOT NULL,
  "gender" varchar,
  "age" integer,
  "role" varchar NOT NULL,
  "first_join" timestamptz
  "registered" boolean
);

CREATE TABLE "server" (
  "name" varchar PRIMARY KEY,
  "type" varchar NOT NULL,
  "last_started_at" timestamptz
);

CREATE TABLE "server_event_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_time" timestamptz NOT NULL,
  "server" varchar NOT NULL,
  "player_uuid" varchar(36),
  "event" varchar NOT NULL,
  "detail" varchar
);

ALTER TABLE "server" ADD FOREIGN KEY ("type") REFERENCES "server_types" ("name");

ALTER TABLE "player" ADD FOREIGN KEY ("role") REFERENCES "player_roles" ("name");

ALTER TABLE "server_event_logs" ADD FOREIGN KEY ("event") REFERENCES "event_types" ("name");

ALTER TABLE "server_event_logs" ADD FOREIGN KEY ("server") REFERENCES "server" ("name");

ALTER TABLE "player_sessions" ADD FOREIGN KEY ("player") REFERENCES "player" ("uuid");

ALTER TABLE "server_event_logs" ADD FOREIGN KEY ("player_uuid") REFERENCES "player" ("uuid");

ALTER TABLE "player_sessions" ADD FOREIGN KEY ("server") REFERENCES "server" ("name");
